### ISSUE TITLE
Vergleichstabelle: Fehler beim Vergleich von Daten

### ISSUE THREAD

**Issue by ClaudiaMayo** [brythnl/CCINFO#81]
Fall A: wird nicht angezeigt, wenn Datum sich ändert

Fall B: es wird angezeigt, aber mit Einheit €

**Comment by brythnl** [comment]
@ClaudiaMayo Wann passiert Fall A?

**Comment by brythnl** [comment]
Fall A tritt auf, wenn es nur um eine Änderung von Tagen geht, welche nicht relevant ist.
Fall B ist gefixt.
